version: "3.9"
services:
  ## 反向解析服务
  ddns:
    container_name: ddns
    image: jeessy/ddns-go
    ports:
      - 9100:9876
    restart: always
    volumes:
      - $CONFIG/ddns:/root
    labels:
      - "traefik.http.routers.ddns.rule=Host(`ddns.jiahangchun.icu`)"

  # 网关服务
  traefik:
    container_name: traefik
    image: traefik:v3.0.0
    restart: always
    ports:
      - 9001:9001
      - 1443:1443
      - 3307:3307
    labels:
      - "traefik.http.routers.traefik-dashboard.rule=Host(`dashboard.jiahangchun.icu`)"
      - "traefik.http.routers.traefik-dashboard.service=dashboard@internal"
      - "traefik.http.routers.traefik-dashboard-api.rule=Host(`dashboard.jiahangchun.icu`) && PathPrefix(`/api`)"
      - "traefik.http.routers.traefik-dashboard-api.service=api@internal"
      - "traefik.http.middlewares.gzip.compress=true"
      - "traefik.http.routers.traefik-dashboard.middlewares=gzip@docker"
      - "traefik.http.routers.traefik-dashboard-api.middlewares=gzip@docker"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/traefik.yml:ro
#      # 会产生权限覆盖问题，需要600权限
      - $CONFIG/acme:/etc/traefik/acme
    environment:
      - TENCENTCLOUD_SECRET_ID=${SECRET_ID}
      - TENCENTCLOUD_SECRET_KEY=${SECRET_KEY}
    healthcheck:
      test: [ "CMD-SHELL", "wget -q --spider --proxy off localhost:8082/ping || exit 1" ]
      interval: 3s
      retries: 10
    networks:
      - traefik
    depends_on:
      - ddns



  # 测试   服务
  whoami:
    container_name: whoami
    image: containous/whoami
    restart: always
    labels:
      - "traefik.http.routers.whoami.rule=Host(`whoami.jiahangchun.icu`)"
      - "traefik.http.routers.whoami.entrypoints=https"
      - "traefik.http.routers.whoami.tls=true"
      - "traefik.http.routers.whoami.tls.certresolver=default"
    networks:
      - traefik
    depends_on:
      - traefik

#  # 导航服务
#  flare:
#    container_name: flare
#    image: soulteary/flare
#    restart: always
#    command: flare
#    volumes:
#      - $CONFIG/flare:/app
#    labels:
#      - "traefik.http.routers.flare.rule=Host(`flare.jiahangchun.icu`)"
#    networks:
#      - traefik
#    depends_on:
#      traefik:
#        condition: service_healthy
#
#
#
#  # 知识库
#  bookstack:
#    image: linuxserver/bookstack
#    container_name: bookstack
#    environment:
#      - PUID=1000
#      - PGID=1000
#      - DB_HOST=bookstack_db
#      - DB_USER=bookstack
#      - DB_PASS=password
#      - DB_DATABASE=bookstackapp
#      - APP_LANG=zh_CN
#      - APP_URL=http://bookstack.jiahangchun.icu:9001/
#      - WKHTMLTOPDF=/usr/bin/wkhtmltopdf
#      # Mail Setting
#      - MAIL_DRIVER=smtp
#      - MAIL_FROM=jiahangchun@163.com
#      - MAIL_FROM_NAME="XXXX知识库"
#      # SMTP mail options
#      - MAIL_HOST=smtpdm.aliyun.com
#      - MAIL_PORT=465
#      - MAIL_USERNAME=service@example.com
#      - MAIL_PASSWORD=password
#      - MAIL_ENCRYPTION=ssl
#    volumes:
#      - $DATA/bookstack:/config
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.bookstack.rule=Host(`bookstack.jiahangchun.icu`)"
#      - "traefik.http.routers.bookstack.entrypoints=http"
#    restart: unless-stopped
#    depends_on:
#      - bookstack_db
#    networks:
#      - traefik
#
#
#
#
#  bookstack_db:
#    image: linuxserver/mariadb
#    container_name: bookstack_db
#    environment:
#      - PUID=1000
#      - PGID=1000
#      - MYSQL_ROOT_PASSWORD=yourdbpass
#      - TZ=Asia/Shanghai
#      - MYSQL_DATABASE=bookstackapp
#      - MYSQL_USER=bookstack
#      - MYSQL_PASSWORD=password
#    volumes:
#      - $DATA/mariadb:/config
#    restart: unless-stopped
#    networks:
#      - traefik
#
#  # docker 私有仓库 直接使用 nexus3 代替
#  # https://docker-practice.github.io/zh-cn/repository/registry.html
##  registry:
##    ports:
##      - 9105:5000
##    volumes:
##      - $DATA/registry:/var/lib/registry
##    restart: always
##    logging:
##      options:
##        max-size: 1g
##    labels:
##      - "traefik.enable=true"
##      - "traefik.http.routers.dockerRegistry.rule=Host(`dockerRegistry.jiahangchun.icu`)"
##      - "traefik.http.routers.dockerRegistry.entrypoints=http"
##    image: registry
##    networks:
##      - traefik
#
#
#  mysql:
#    restart: always
#    image: mysql:8.0.18
#    container_name: mysql-lable
#    #env_file:
#    #  - ./env/mysql.env
#    environment:
#      - MYSQL_ROOT_PASSWORD=123456 # root用户密码
#      - MYSQL_DATABASE=jiahangchun
#      - TZ=Asia/Shanghai
#    volumes:
#      - $DATA/mysql8/log:/var/log/mysql # 映射日志目录，宿主机:容器
#      - $DATA/mysql8/data:/var/lib/mysql # 映射数据目录，宿主机:容器
#      - $CONFIG/mysql/conf.d:/etc/mysql/conf.d # 映射配置目录，宿主机:容器
#      - /etc/localtime:/etc/localtime:ro # 让容器的时钟与宿主机时钟同步，避免时间的问题，ro是read only的意思，就是只读。
#    labels:
#      - "traefik.enable=true"
#      - "traefik.tcp.routers.mysql.rule=HostSNI(`*`)"
#      - "traefik.tcp.routers.mysql.entrypoints=mysql"
#    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
#    ports:
#      - 9107:3306
#    networks:
#      - traefik
#
#  #docker控制面板
#  # 访问 http://portaineree.jiahangchun.icu:9001/ 即可访问，这边端口是 未被映射出来的端口,也就是原始端口
#  # 这边还需要手动 指定端口，可能 portainer 暴露了多个端口，导致 traefik listener文件 随机选取了一个
#  # 参考 官方文档：https://doc.traefik.io/traefik/providers/docker/
#  portainer-ee:
#    ports:
#      - 9108:8000 # 官方文档上的地址是这个
#      - 9109:9443
#      - 9110:9000 #这个才是webUI的端口
#    container_name: portainer
#    restart: always
#    command: -H unix:///var/run/docker.sock
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#      - $DATA/portainer:/data
#    image: portainer/portainer-ee:latest
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.portaineree.rule=Host(`portaineree.jiahangchun.icu`)"
#      - "traefik.http.services.portaineree.loadbalancer.server.port=9000"
#    networks:
#      - traefik
#    depends_on:
#      - traefik
#
##快照库 github package 替換調了
##  nexus:
##    image: sonatype/nexus3
##    labels:
##      - "traefik.enable=true"
##      - "traefik.http.routers.nexus.rule=Host(`nexus.jiahangchun.icu`)"
##      - "traefik.http.services.nexus.loadbalancer.server.port=8081"
##    volumes:
##      - $DATA/nexus/nexus-data:/nexus-data
##    restart: always
##    ports:
##      - 9112:8081
##    networks:
##      - traefik
##    depends_on:
##      - traefik
#
#
##新增自定義服務
#  weixin_service:
#    image: ghcr.io/jiahangchun/weixin:main
#    container_name: weixin_service
#    ports:
#      - 9113:8080
#    volumes:
#      - $DATA/weixin_service:/app
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.weixin.rule=Host(`weixin.jiahangchun.icu`)"
#      - "traefik.http.services.weixin.loadbalancer.server.port=8080"
#    networks:
#      - traefik
#    restart: always
#
#  #  http://127.0.0.1:9114/nacos
#  nacos:
#    image: nacos/nacos-server
#    container_name: nacos-standalone
#    volumes:
#      - $DATA/nacos/standalone-logs/:/home/nacos/logs
#    labels:
#      # 不暴露外网
#      #- "traefik.http.routers.nacos.rule=Host(`nacos.jiahangchun.icu`)"
#      #- "traefik.http.services.nacos.loadbalancer.server.port=8848"
#      - "traefik.enable=true"
#    #env_file:
#    # - ./env/nacos-standlone-mysql.env
#    ports:
#      - "9114:8848"
#      # 神經病 nacos 默認開啓端口
#      - "10114:9848"
#      - "10115:9849"
#      - "8115:7848"
#    environment:
#      - PREFER_HOST_MODE=hostname
#      - MODE=standalone
#      - SPRING_DATASOURCE_PLATFORM=mysql
#      - MYSQL_SERVICE_HOST=mysql
#        # 这里还要容器的原始端口阿
#      - MYSQL_SERVICE_PORT=3306
#      - MYSQL_SERVICE_DB_NAME=nacos_config
#      - MYSQL_SERVICE_USER=root
#      - MYSQL_SERVICE_PASSWORD=123456
#    networks:
#      - traefik
#    restart: always
#
#  # 待验证
#  ##########################################监控##############################################
#  node-exporter:
#    image: quay.io/prometheus/node-exporter
#    container_name: node-exporter
#    hostname: node-exporter
#    restart: always
#    labels:
#      - "traefik.http.routers.exporter.rule=Host(`exporter.jiahangchun.icu`)"
#    ports:
#      - "9101:9100"
#    networks:
#      - traefik
#
## 网络原因
##  cadvisor:
##    image: gcr.io/cadvisor/cadvisor:latest
##    container_name: cadvisor
##    hostname: cadvisor
##    restart: always
##    volumes:
##      - /:/rootfs:ro
##      - /var/run:/var/run:rw
##      - /sys:/sys:ro
##      - /var/lib/docker/:/var/lib/docker:ro
##      - /var/lib/docker/:/var/lib/docker:ro
##    ports:
##      - "9102:8080"
##    networks:
##      - traefik
## 需要先安装 cadvisor
#  prometheus:
#    image: prom/prometheus
#    container_name: prometheus
#    hostname: prometheus
#    restart: always
#    volumes:
#      - $CONFIG/monitor/prometheus.yml:/etc/prometheus/prometheus.yml
#      - $CONFIG/monitor/node_down.yml:/etc/prometheus/node_down.yml
#    ports:
#      - "9103:9090"
#    labels:
#      - "traefik.http.routers.prometheus.rule=Host(`prometheus.jiahangchun.icu`)"
#    networks:
#      - traefik
##    depends_on:
##      - cadvisor
##      - node-exporter
#
#
#  grafana:
#    image: grafana/grafana
#    container_name: grafana
#    hostname: grafana
#    environment:
#      - GF_SECURITY_ADMIN_PASSWORD=jiahangchun
#    volumes:
#      - '$DATA/grafana/:/var/lib/grafana'
#    restart: always
#    labels:
#      - "traefik.http.routers.grafana.rule=Host(`grafana.jiahangchun.icu`)"
#    ports:
#      - "9104:3000"
#    depends_on:
#      - prometheus
#    networks:
#      - traefik


networks:
  traefik:
    external: true
