services:
  # 网关服务
  traefik:
    container_name: traefik
    image: traefik:v3.0.0
    restart: always
    ports:
      - 12001:12001
      - 1314:1314
      - 3307:3307
    labels:
      - "traefik.http.routers.traefik-dashboard.rule=Host(`dashboard.jiahangchun.icu`)"
      - "traefik.http.routers.traefik-dashboard.service=dashboard@internal"
      - "traefik.http.routers.traefik-dashboard-api.rule=Host(`dashboard.jiahangchun.icu`) && PathPrefix(`/api`)"
      - "traefik.http.routers.traefik-dashboard-api.service=api@internal"
      - "traefik.http.middlewares.gzip.compress=true"
      - "traefik.http.routers.traefik-dashboard.middlewares=gzip@docker"
      - "traefik.http.routers.traefik-dashboard-api.middlewares=gzip@docker"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/traefik.yml:ro
      - ./config/traefik/:/etc/traefik/config:ro
      - /home/jiahangchun/.acme.sh/jiahangchun.icu_ecc/:/data/ssl/:ro
    healthcheck:
      test: [ "CMD-SHELL", "wget -q --spider --proxy off localhost:8082/ping || exit 1" ]
      interval: 3s
      retries: 10
    networks:
      - traefik

  # 测试   服务
  whoami:
    container_name: whoami
    image: containous/whoami
    restart: always
    labels:
      - "traefik.http.routers.whoami.rule=Host(`whoami.jiahangchun.icu`)"
    networks:
      - traefik
    depends_on:
      - traefik


#  ollama:
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              count: all
#              capabilities:
#                - gpu
#    volumes:
#      - C://jiahangchun//idea//code//docker//data//ollama:/root/.ollama
#    ports:
#      - 11434:11434
#    container_name: ollama
#    image: ollama/ollama
#    networks:
#      - traefik
#    depends_on:
#      - traefik

  open-webui:
    ports:
      - 3000:8080
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - C://jiahangchun//idea//code//docker//data//open-webui:/app/backend/data
    container_name: open-webui
    restart: always
    image: ghcr.io/open-webui/open-webui:main
    networks:
      - traefik
    depends_on:
      - traefik

networks:
  traefik:
    external: true
