#https://zhuanlan.zhihu.com/p/383819418

[tls]
    [tls.options]
        [tls.options.default]
            minVersion = "VersionTLS12"
            maxVersion = "VersionTLS12"
        [tls.options.test-tls13]
            minVersion = "VersionTLS13"
            cipherSuites = [
                "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
                "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
                "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305",
                "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305",
                "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
                "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
            ]

    [[tls.certificates]]
    # 此目录为docker-compose配置中，映射宿主机目录，证书生成在下一个步骤
        certFile = "/data/ssl/jiahangchun.icu.cer"
        keyFile = "/data/ssl/jiahangchun.icu.key"