## STATIC CONFIGURATION
log:
  level: DEBUG
#  format: json
#  filePath: ./traefik.log


api:
  insecure: true
  dashboard: true
  debug: false

# 开放端口
entryPoints:
  http:
    address: ":12001"


ping:
  entryPoint: "ping"

providers:
  #https://doc.traefik.io/traefik/providers/docker/
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: true
    watch: true
    #500毫秒超时 未相应配置
    httpClientTimeout: 500
  file:
    watch: true
    directory: /etc/traefik/config
    debugLogGeneratedTemplate: true


