## STATIC CONFIGURATION
log:
  level: DEBUG
#  format: json
#  filePath: ./traefik.log


api:
  insecure: true
  dashboard: true
  debug: false

# 开放端口
entryPoints:
  http:
    address: ":9001"
  https:
    address: ":1443"
  mysql:
    address: ":3307"
  ping:
    address: ":8082"


ping:
  entryPoint: "ping"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: true
  file:
    watch: true
    directory: ./config/traefik
    debugLogGeneratedTemplate: true


