## STATIC CONFIGURATION
log:
  level: INFO

accessLog:
  filePath: /traefik.log
  format: json
  fields:
    defaultMode: keep

api:
  insecure: true
  dashboard: true

entryPoints:
  http:
    address: ":9001"
  https:
    address: ":1443"
  mysql:
    address: ":3307"
  metrics:
    address: ":8082"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false


