## STATIC CONFIGURATION
log:
  level: DEBUG
#  format: json
#  filePath: ./traefik.log


api:
  insecure: true
  dashboard: true

# 开放端口
entryPoints:
  http:
    address: ":9001"
  https:
    address: ":1443"
    http:
      tls:
        certResolver: default
        domains:
          - main: "www.jiahangchun.icu"
            sans:
              - "whoami.jiahangchun.icu"
              - "*.jiahangchun.icu"
  mysql:
    address: ":3307"
  ping:
    address: ":8082"

ping:
  entryPoint: "ping"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: true


certificatesResolvers:
  default:
    acme:
      email: jiahangchun@163.com
      storage: acme.json
      dnsChallenge:
        provider: tencentcloud
