## STATIC CONFIGURATION
log:
  level: DEBUG
#  format: json
#  filePath: ./traefik.log


api:
  insecure: true
  dashboard: true
  debug: false

# 开放端口
entryPoints:
  http:
    address: ":9001"
#    http:
#      redirections:
#        entryPoint:
#          to: https
#          scheme: https
#          permanent: true
  https:
    address: ":1443"
  mysql:
    address: ":3307"
  ping:
    address: ":8082"


ping:
  entryPoint: "ping"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: true
    defaultRule: "Host(`{{ .Name }}.jiahangchun.icu`)"
  file:
    watch: true
    directory: /etc/traefik/config
    debugLogGeneratedTemplate: true


