name: Docker容器自动启动
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build_job:
    name: 切出代码
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
    # 利用action把build好的文件上传到服务器/home/jiahangchun/code/action_file路径下,需要确认此目录已在服务端创建
      - name: deploy file to server
        uses: wlixcc/SFTP-Deploy-Action@v1.0 
        with:  
          username: '${{ secrets.REMOTE_IP_ADDRESS }}'  
          server: '${{ secrets.REMOTE_IP_ADDRESS }}'
          ssh_private_key: ${{ secrets.REMOTE_RSA }}
          local_path: './'
          remote_path: '/home/jiahangchun/code/action_file'

