name: Docker容器自动启动
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build_job:
    name: docker部署三方
    runs-on: ubuntu-latest
    steps:
      - name: 切分支
        uses: actions/checkout@v4
    # 利用action把build好的文件上传到服务器/home/jiahangchun/code/action_file路径下,需要确认此目录已在服务端创建
      - name: 将文件转移到服务器
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:  
          username: '${{ secrets.REMOTE_USER_NAME }}'  
          server: '${{ secrets.REMOTE_IP_ADDRESS }}'
          port: '${{ secrets.REMOTE_PORT }}'
          password: '${{ secrets.REMOTE_PASSWORD }}'
          local_path: './*'
          remote_path: '${{ secrets.REMOTE_FILE_TARGET }}'
      - name: 远程执行命令，将项目启动起来
        uses: garygrossgarten/github-action-ssh@release
        with:
          # 先进入主目录，然后将密码传给 sh ,最后启动
          command: cd '${{ secrets.REMOTE_FILE_TARGET }}' && echo '${{ secrets.REMOTE_PASSWORD }}' | sh -S start.sh
          host: '${{ secrets.REMOTE_IP_ADDRESS }}'
          username: '${{ secrets.REMOTE_USER_NAME }}'
          port: '${{ secrets.REMOTE_PORT }}'
          password: '${{ secrets.REMOTE_PASSWORD }}'

