name: Docker容器自动启动
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build_job:
    name: docker部署三方
    runs-on: ubuntu-latest
    steps:
      - name: 切分支
        uses: actions/checkout@v4
      - name: 参数确认
        run: echo ${{ secrets.REMOTE_USER_NAME }} ${{ secrets.REMOTE_USER_NAME1 }}
    # 利用action把build好的文件上传到服务器/home/jiahangchun/code/action_file路径下,需要确认此目录已在服务端创建
      - name: 将文件转移到服务器
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:  
          username: '${{ secrets.REMOTE_USER_NAME }}'  
          server: '${{ secrets.REMOTE_IP_ADDRESS }}'
          port: '${{ secrets.REMOTE_PORT }}'
          password: '${{ secrets.REMOTE_PASSWORD }}'
          local_path: './*'
          remote_path: '${{ secrets.REMOTE_FILE_TARGET }}'

